apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: shell-demo
  name: shell-demo
  namespace: shell-demo
spec:
  selector:
    matchLabels:
      app-name: shell-demo
  template:
    metadata:
      labels:
        app-name: shell-demo
    spec:
      serviceAccountName: shell-demo-runner
      containers:
      - name: shell-demo
        env:
        - name: SECRET_ENVVAR
          valueFrom:
            secretKeyRef: 
              name: demo-secret
              key: oneline # name of the key in the configmap
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/config
        command:
          - /usr/bin/bash
          - -c
          - "sleep 1000"
        image: fedora:36
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
      volumes:
        - name: secret-volume
          secret:
            secretName: demo-secret
