apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: shell-demo
  name: shell-demo
  namespace: shell-demo
spec:
  selector:
    matchLabels:
      app-name: shell-demo
  template:
    metadata:
      labels:
        app-name: shell-demo
    spec:
      serviceAccountName: shell-demo-runner
      containers:
      - name: shell-demo
        command:
          - /usr/bin/bash
          - -c
          - "while true; do sleep 1000; done"
        image: fedora:36
        imagePullPolicy: IfNotPresent
