apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-name: shell-demo
  name: shell-demo
  namespace: shell-demo
spec:
  selector:
    matchLabels:
      app-name: shell-demo
  template:
    metadata:
      labels:
        app-name: shell-demo
    spec:
      hostPID: true
      hostNetwork: true
      serviceAccountName: shell-demo-runner
      containers:
      - name: shell-demo
        command:
          - /usr/bin/bash
          - -c
          - "echo \"echo Run the command %%% nsenter --mount=/proc/1/ns/mnt -- /bin/bash %%% to bust root.\" >> /root/.bashrc; while true; do sleep 1000; done"
        image: fedora:36
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
